default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5432

development:
  <<: *default
  database: appname_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: appname_test
  username: postgres
  password: postgres
  host: 127.0.0.1
